Repository freeCodeCamp/chapter, pull requests merged in 2022-08, with the labels that each got.

#1322 refactor: use isDirty to disable save button
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
Labels: status: ready for review

#1298 feat: add Authorized decorator to updateEvent resolver
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1305 feat: seed chapter 2 admin
  CONTRIBUTING.md
  cypress.config.ts
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/chapters/[chapterId]/edit.cy.ts
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/e2e/dashboard/sponsors.cy.ts
  cypress/e2e/dashboard/venues.cy.ts
  cypress/e2e/events/[eventId].cy.ts
  server/prisma/generator/factories/user.factory.ts
  server/prisma/generator/seed.ts
  server/prisma/generator/setupRoles.ts
Labels: status: ready for review

#1331 chore: remove nullable from rsvpEvent
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1355 fix: add label to invite only icon
  client/src/components/EventCard.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: UI/UX, status: ready for review

#1293 feat: integrate auth0
  .env.example
  .github/workflows/cypress-docker.yaml
  .github/workflows/cypress.yaml
  .gitignore
  .gitpod.yml
  CONTRIBUTING.md
  client/.env.local.example
  client/.example.env.local
  client/package.json
  client/src/components/PageLayout/Header.tsx
  client/src/hooks/useSession.ts
  client/src/modules/auth/store/index.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/dashboard/shared/components/Layout.tsx
  client/src/pages/_app.tsx
  cypress.config.ts
  cypress/e2e/auth/login.cy.ts
  cypress/e2e/chapters/[chapterId].cy.ts
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/chapters/[chapterId]/edit.cy.ts
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/e2e/dashboard/sponsors.cy.ts
  cypress/e2e/dashboard/venues.cy.ts
  cypress/e2e/events/[eventId].cy.ts
  cypress/support/commands.ts
  docker-compose.ci.yml
  docker-compose.yml
  package-lock.json
  package.json
  scripts/change-user.js
  scripts/dev-data/.gitkeep
  scripts/postInstall.js
  server/package.json
  server/prisma/generator/factories/user.factory.ts
  server/prisma/schema.prisma
  server/src/app.ts
  server/src/controllers/Auth/check-jwt.ts
  server/src/controllers/Auth/middleware.ts
  server/src/util/auth0.ts
  server/src/util/sessions.ts
Labels: API, status: ready for review

#1345 feat: venue create with admined chapters dropdown
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/auth/graphql/mutations.ts
  client/src/modules/auth/graphql/queries.ts
  client/src/modules/dashboard/Venues/components/VenueForm.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  client/src/pages/dashboard/venues/new.tsx
  cypress/e2e/dashboard/venues.cy.ts
  server/src/controllers/User/resolver.ts
  server/src/controllers/index.ts
Labels: status: ready for review

#1341 chore: seed less random tags
  server/prisma/generator/factories/events.factory.ts
Labels: status: ready for review

#1394 feat: display add new venue button only for users with chapter admin permission
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
Labels: status: ready for review

#1400 Adding/themes to chapter
  client/src/pages/_app.tsx
  client/src/styles/themes.ts
Labels: status: ready for review

#1353 feat: use single field for user name
  client/graphql.schema.json
  client/src/components/LoginRegisterModal.tsx
  client/src/components/PageLayout/Header.tsx
  client/src/generated/graphql.tsx
  client/src/modules/auth/graphql/mutations.ts
  client/src/modules/auth/graphql/queries.ts
  client/src/modules/auth/pages/Register.tsx
  cypress/e2e/auth/login.cy.ts
  cypress/e2e/auth/register.cy.ts
  cypress/e2e/events/[eventId].cy.ts
  cypress/support/commands.ts
  server/prisma/generator/factories/user.factory.ts
  server/prisma/schema.prisma
  server/src/app.ts
  server/src/controllers/Auth/inputs.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Users/resolver.ts
  server/src/controllers/index.ts
  server/src/graphql-types/User.ts
  server/tests/fixtures/users.ts
Labels: status: ready for review

#1396 fix: wait for loading url parameter
  client/src/hooks/useParam.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/util/getId.ts
Labels: status: ready for review

#1432 Remove searchbar
  client/src/components/PageLayout/Header.tsx
Labels: UI/UX, status: ready for review

#1430 feat: chapters dropdown event create
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/pages/dashboard/events/new.tsx
Labels: status: ready for review

#1369 Clear the Empty spaces in /chapter route
  README.md
  client/src/modules/chapters/pages/chaptersPage.tsx
Labels: UI/UX, status: ready for review

#1361 fix: chapter presentation
  client/graphql.schema.json
  client/src/components/ChapterCard.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/home/graphql/queries.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/graphql-types/Chapter.ts
Labels: status: ready for review

#1429 chore: event card responsive representation
  client/src/components/EventCard.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: UI/UX, status: ready for review

#1458 chore: polishing the heading, text and style
  client/src/components/EventCard.tsx
  client/src/components/PageLayout/Header.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#1467 chore: update cypress tests path
  CONTRIBUTING.md
Labels: status: ready for review
