Repository freeCodeCamp/chapter, pull requests merged in 2022-09, with the labels that each got.

#1482 chore: unify imports from /modules/dashboard/Sponsors
  client/src/modules/dashboard/Sponsors/index.ts
  client/src/pages/dashboard/sponsors/[id]/edit.tsx
  client/src/pages/dashboard/sponsors/[id]/index.tsx
  client/src/pages/dashboard/sponsors/index.tsx
  client/src/pages/dashboard/sponsors/new.tsx
Labels: status: ready for review

#1471 chore: remove unused object type
  server/src/controllers/Unsubscribe/inputs.ts
Labels: status: ready for review

#1481 fix: delay rendering until url param is loaded
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: status: ready for review

#1488 docs: add change user commands
  CONTRIBUTING.md
Labels: status: ready for review

#1496 chore: remove the old Auth system
  CONTRIBUTING.md
  client/src/modules/auth/index.ts
  client/src/modules/auth/pages/Login.tsx
  client/src/modules/auth/pages/Register.tsx
  client/src/pages/auth/login.tsx
  client/src/pages/auth/register.tsx
  cypress/e2e/auth/login.cy.ts
  cypress/e2e/auth/register.cy.ts
Labels: status: ready for review

#1506 fix: dirty form when field changes
  client/src/modules/dashboard/Events/components/EventForm.tsx
Labels: UI/UX, status: ready for review

#1509 fix: ensure event start is not after end
  client/src/modules/dashboard/Events/components/EventForm.tsx
Labels: status: ready for review

#1476 fix: events loading inconsistency
  client/src/modules/events/pages/eventsPage.tsx
Labels: status: ready for review

#1516 refactor: remove old auth (JWT) code
  .env.example
  CONTRIBUTING.md
  client/graphql.schema.json
  client/src/components/LoginRegisterModal.tsx
  client/src/generated/graphql.tsx
  client/src/modules/auth/graphql/mutations.ts
  client/src/modules/auth/index.ts
  client/src/modules/auth/pages/Token.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/pages/auth/token.tsx
  cypress.config.ts
  server/src/config/index.ts
  server/src/controllers/Auth/inputs.ts
  server/src/controllers/Auth/resolver.ts
  server/src/services/AuthToken.ts
  server/tests/Auth.test.ts
Labels: API

#1490 chore: friendly message in production
  server/src/app.ts
  server/src/controllers/Auth/middleware.ts
Labels: status: ready for review

#1451 feat: add csrf protection
  server/src/app.ts
Labels: status: ready for review

#1442 feat: allow calendar and event creation
  .gitignore
  client/src/components/PageLayout/Header.tsx
  common/permissions.ts
  package-lock.json
  server/keys/.gitkeep
  server/package.json
  server/prisma/schema.prisma
  server/src/app.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/services/Google.ts
Labels: MVP, Admin, API, status: ready for review

#1505 fix: make dashboard consistent
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
  client/src/modules/dashboard/Users/pages/UsersPage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/e2e/dashboard/venues.cy.ts
Labels: status: ready for review

#1413 fix: restrict 'user ban' functionality to member with ChapterBanUser rule
  common/permissions.ts
  cypress/e2e/dashboard/chapters/users.cy.ts
  server/src/controllers/ChapterUser/resolver.ts
Labels: status: needs update

#1538 refactor: DRY standard bodies
  server/src/services/Google.ts
Labels: status: ready for review

#1542 chore: add skip navigation button
  client/package.json
  client/src/components/PageLayout/Header.tsx
  client/src/components/PageLayout/index.tsx
  client/src/styles/Header.module.css
  package-lock.json
Labels: status: ready for review

#1546 fix: defer loading until the router is ready
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: status: ready for review

#1552 fix: link typo
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
Labels: status: ready for review

#1553 feat: truncate website text
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
Labels: status: ready for review

#1554 fix: non-unique iteration key
  client/src/modules/dashboard/Events/pages/EventPage.tsx
Labels: status: ready for review

#1557 test: use deletable venue for deletion
  cypress/e2e/dashboard/venues.cy.ts
Labels: status: ready for review

#1559 chore: add custom error message
  cypress/support/util.ts
Labels: status: ready for review

#1237 feat(client): delete chapter
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/graphql/mutations.ts
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
Labels: status: ready for review

#1555 test: create sponsor test deflaky
  cypress/e2e/dashboard/sponsors.cy.ts
Labels: status: ready for review

#1562 chore: remove unrequired inputs and polish some style
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Sponsors/components/SponsorForm.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
Labels: status: ready for review

#1563 feat: display toast after sending email
  client/src/modules/dashboard/Events/components/SendEmailModal.tsx
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#1556 test: change event venue deflaky
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#1416 feat: add decorator for CanBeBanned
  client/src/modules/dashboard/shared/components/DashboardLoading.tsx
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/support/commands.ts
  server/src/controllers/ChapterUser/resolver.ts
Labels: status: needs update

#1568 test: allow waiting for expected no. of emails
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/support/commands.ts
Labels: status: ready for review

#1567 chore: create user profile
  client/graphql.schema.json
  client/src/components/PageLayout/Header.tsx
  client/src/generated/graphql.tsx
  client/src/modules/auth/graphql/mutations.ts
  client/src/modules/profiles/index.tsx
  client/src/modules/profiles/pages/userProfile.tsx
  client/src/pages/profile/index.ts
  server/prisma/schema.prisma
  server/src/controllers/User/resolver.ts
Labels: status: ready for review

#1521 chore: policy page
  client/src/modules/policy/index.ts
  client/src/modules/policy/pages/policyPage.tsx
  client/src/pages/_app.tsx
  client/src/pages/policy/index.tsx
Labels: status: ready for review

#1578 chore: swap event placeholders
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
Labels: status: ready for review

#1582 chore: polish venue and form spacing
  client/src/modules/dashboard/Venues/components/VenueForm.tsx
  client/src/styles/Form.module.css
Labels: status: ready for review

#1583 chore: add consistent space to the forms
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Sponsors/components/SponsorForm.tsx
Labels: status: ready for review

#1584 chore: consistent color scheme
  client/src/components/Modal.tsx
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: status: ready for review

#1594 feat: login when rsvping
  client/src/components/PageLayout/Header.tsx
  client/src/hooks/useAuth.ts
  client/src/hooks/useSession.ts
  client/src/modules/auth/store/index.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/modules/profiles/pages/userProfile.tsx
Labels: status: ready for review

#1595 chore: create profile form
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/auth/graphql/mutations.ts
  client/src/modules/profiles/component/ProfileForm.tsx
  server/src/controllers/User/input.ts
  server/src/controllers/User/resolver.ts
Labels: status: ready for review

#1602 fix: updating chapter on event changes
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
Labels: status: ready for review

#1580 chore: replace event placeholder in venue page
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Venues/graphql/queries.ts
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  server/src/controllers/Venue/resolver.ts
  server/src/graphql-types/Venue.ts
Labels: status: ready for review

#1605 feat: limit ability to delete chapter to the owner
  common/permissions.ts
  cypress/e2e/dashboard/chapters/[chapterId]/edit.cy.ts
  cypress/support/commands.ts
  server/src/controllers/Chapter/resolver.ts
Labels: status: ready for review

#1601 feat: login when rsvping (take two)
  client/src/components/PageLayout/Header.tsx
  client/src/hooks/useAuth.ts
  client/src/hooks/useSession.ts
  client/src/modules/auth/store/index.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/modules/profiles/pages/userProfile.tsx
Labels: API, status: ready for review

#1589 feat: ability to change name in profile
  client/src/modules/profiles/component/ProfileForm.tsx
  client/src/modules/profiles/pages/userProfile.tsx
Labels: status: ready for review

#1604 feat: add required inputs
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  server/src/controllers/Events/inputs.ts
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1572 feat: hide dashboards
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Venues/graphql/queries.ts
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/events/graphql/queries.ts
  client/src/modules/events/pages/eventPage.tsx
  common/permissions.ts
  cypress/e2e/dashboard/all.cy.ts
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/support/commands.ts
  server/src/app.ts
  server/src/authorization/index.ts
  server/src/common-types/gql.ts
  server/src/controllers/Auth/middleware.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Venue/resolver.ts
  server/tests/authorization.test.ts
  server/tests/fixtures/venues.ts
Labels: UI/UX, API, status: ready for review

#1579 feat: update staging deploy procress
  .github/workflows/reset-dev-db.yml
Labels: status: blocked

#1623 chore: change chapter user to a button for consistancy
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
Labels: status: ready for review

#1606 Connecting venue info to chapter card
  client/graphql.schema.json
  client/src/components/ChapterCard.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/home/graphql/queries.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/graphql-types/Chapter.ts
  server/src/graphql-types/Event.ts
Labels: status: ready for review

#1624 chore: add colors to call to actions buttons in menu
  client/src/components/PageLayout/Header.tsx
Labels: status: ready for review

#1625 fix: allow url and streaming_url to be optional
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/support/commands.ts
  cypress/tsconfig.json
  server/src/controllers/Events/inputs.ts
  server/src/controllers/Events/resolver.ts
Labels: status: merge conflict
