Repository freeCodeCamp/chapter, pull requests merged in 2022-10, with the labels that each got.

#1643 fix: hide sponsor ops in mobile view
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
Labels: status: ready for review

#1641 feat: change permission for displaying edit sponsor form
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Sponsors/components/SponsorForm.tsx
  client/src/modules/dashboard/Sponsors/graphql/queries.ts
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  cypress/e2e/dashboard/pages-needing-permission.cy.ts
  server/src/controllers/Sponsors/resolver.ts
Labels: status: ready for review

#1645 feat: use nested layout for dashboard
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/NewSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
  client/src/modules/dashboard/Users/pages/UsersPage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  client/src/modules/dashboard/shared/components/DashboardLoading.tsx
  client/src/pages/_app.tsx
Labels: status: ready for review

#1632 Refactor: remove events tags requirements from fields and resolvers
  client/graphql.schema.json
  client/src/components/EventCard.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/events/graphql/queries.ts
  client/src/modules/home/graphql/queries.ts
  client/tests/EventCard.test.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  server/prisma/generator/factories/events.factory.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/inputs.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Sponsors/resolver.ts
  server/src/controllers/Venue/resolver.ts
  server/src/graphql-types/Event.ts
  server/src/graphql-types/EventReminder.ts
Labels: status: ready for review

#1647 feat: navigate to the next required page creation, after finishing creating desired page
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
Labels: status: ready for review

#1674 refactor: simplify updateEvent resolver
  server/src/controllers/Events/resolver.ts
Labels: API

#1682 test: reduce flakiness
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#1680 refactor: move HeaderMenu out of header
  client/src/components/PageLayout/Header.tsx
  client/src/components/PageLayout/HeaderMenu.tsx
Labels: status: ready for review

#1687 chore: add a problem and a solution for sync .env file
  CONTRIBUTING.md
Labels: status: ready for review

#1700 chore: clear duplication on login section
  CONTRIBUTING.md
Labels: status: ready for review

#1656 feat: polish status of the event
  client/src/components/EventCard.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#1716 docs: move finding issues to faq
  CONTRIBUTING.md
Labels: Documentation, status: ready for review

#1501 fix: send event creation notification message
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1715 Refactor: chapter image_url to banner_url
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  client/src/modules/home/graphql/queries.ts
  cypress/e2e/dashboard/chapters/[chapterId]/edit.cy.ts
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  server/prisma/generator/factories/chapters.factory.ts
  server/prisma/schema.prisma
  server/src/controllers/Chapter/inputs.ts
  server/src/graphql-types/Chapter.ts
Labels: status: ready for review

#1686 refactor: tidy and separate concerns of venueform
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/NewSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
  client/src/modules/dashboard/Users/pages/UsersPage.tsx
  client/src/modules/dashboard/Venues/components/VenueForm.tsx
  client/src/modules/dashboard/Venues/graphql/mutations.ts
  client/src/modules/dashboard/Venues/index.ts
  client/src/modules/dashboard/Venues/pages/ChapterNewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  client/src/modules/dashboard/Venues/utils.ts
  client/src/modules/dashboard/shared/components/DashboardLoading.tsx
  client/src/pages/dashboard/chapters/[id]/new-venue.tsx
  cypress/support/commands.ts
  cypress/support/e2e.ts
  server/src/controllers/Venue/inputs.ts
  server/src/controllers/Venue/resolver.ts
Labels: UI/UX, API, status: ready for review

#1708 fix: change confirm button text to 'yes, im sure'
  client/src/modules/profiles/pages/userProfile.tsx
Labels: status: ready for review

#1644 feat: event dashboard improvements
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/support/commands.ts
Labels: status: ready for review

#1733 feat: change Add Sponsor button colorscheme for consistency
  client/src/modules/dashboard/Events/components/EventForm.tsx
Labels: status: ready for review

#1726 feat: more descriptive chapter deletion modal
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
Labels: status: ready for review

#1734 feat: gracefully fallback to default when event image fails to render
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: status: needs update

#1728 fix: don't send new event invite to users banned from chapter
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1727 feat: add share button for events
  client/src/components/SharePopOver.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
Labels: status: ready for review

#1626 chore: refactor create event form
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#1747 fix: render only when ready
  client/src/hooks/useParam.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx
  client/src/modules/dashboard/Venues/pages/ChapterNewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/pages/_app.tsx
Labels: UI/UX

#1743 feat: invite link shows join modal
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/events/pages/eventPage.tsx
  cypress/e2e/chapters/[chapterId].cy.ts
  cypress/e2e/events/[eventId].cy.ts
  server/tests/Mailer.test.ts
Labels: UI/UX, status: ready for review

#1729 feat: remove rsvps from banned user
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  cypress/e2e/dashboard/chapters/users.cy.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/util/updateCalendarEventAttendees.ts
  server/src/util/updateEventWaitlist.ts
Labels: status: ready for review

#1762 chore: use expectNoErrors util
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/chapters/[chapterId]/edit.cy.ts
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#1744 chore: use fixtures in cypress
  cypress/e2e/chapters/[chapterId].cy.ts
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/chapters/[chapterId]/edit.cy.ts
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/e2e/dashboard/dashboard-index.cy.ts
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/e2e/dashboard/pages-needing-permission.cy.ts
  cypress/e2e/dashboard/sponsors.cy.ts
  cypress/e2e/dashboard/users.cy.ts
  cypress/e2e/dashboard/venues.cy.ts
  cypress/e2e/events/[eventId].cy.ts
  cypress/e2e/unsubscribe.cy.ts
  cypress/fixtures/chapters.json
  cypress/fixtures/events.json
  cypress/fixtures/venues.json
Labels: status: ready for review

#1769 feat: fix flashing img while loading image
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: status: ready for review

#1787 chore: improve error message
  cypress/support/util.ts
Labels: status: ready for review

#1633 feat: allow users to leave chapters
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/mutations.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  cypress/e2e/chapters/[chapterId].cy.ts
  cypress/e2e/events/[eventId].cy.ts
  cypress/support/commands.ts
  server/src/controllers/ChapterUser/resolver.ts
Labels: status: ready for review

#1730 feat: re-implement is_bannable logic
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/support/util.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/graphql-types/ChapterUser.ts
  server/src/util/chapterBans.ts
  server/tests/chapterBans.test.ts
Labels: status: ready for review

#1784 refactor: single user middleware
  server/src/app.ts
  server/src/controllers/Auth/middleware.ts
Labels: status: ready for review

#1788 refactor: waitlist updates
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/util/waitlist.ts
Labels: status: ready for review

#1792 refactor: split EventFrom into components
  client/src/modules/dashboard/Events/components/EventChapterSelect.tsx
  client/src/modules/dashboard/Events/components/EventDatesForm.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/components/EventSponsorsForm.tsx
  client/src/modules/dashboard/Events/components/EventVenueForm.tsx
Labels: status: ready for review

#1756 feat(server): query for personal information
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  server/src/controllers/User/resolver.ts
  server/src/graphql-types/User.ts
Labels: status: needs update

#1804 feat: chapter subscription doesn't affect events
  client/src/modules/chapters/pages/chapterPage.tsx
  cypress/e2e/chapters/[chapterId].cy.ts
  cypress/e2e/unsubscribe.cy.ts
  server/reminders/reminders.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Unsubscribe/resolver.ts
Labels: status: ready for review

#1807 feat: validate event dates
  client/src/modules/dashboard/Events/components/EventDatesForm.tsx
Labels: status: ready for review
