Repository freeCodeCamp/chapter, pull requests merged in 2022-11, with the labels that each got.

#1808 refactor: separate init and seed
  .gitignore
  cypress.config.ts
  package.json
  server/package.json
  server/prisma/init/factories/chapterRoles.factory.ts
  server/prisma/init/factories/eventRoles.factory.ts
  server/prisma/init/factories/instanceRoles.factory.ts
  server/prisma/init/factories/rsvpTypes.factory.ts
  server/prisma/init/init.ts
  server/prisma/seed/factories/chapters.factory.ts
  server/prisma/seed/factories/events.factory.ts
  server/prisma/seed/factories/rsvps.factory.ts
  server/prisma/seed/factories/sponsors.factory.ts
  server/prisma/seed/factories/user.factory.ts
  server/prisma/seed/factories/venues.factory.ts
  server/prisma/seed/lib/random.ts
  server/prisma/seed/lib/util.ts
  server/prisma/seed/resetUsers.ts
  server/prisma/seed/seed.ts
  server/prisma/seed/setupRoles.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/InstanceRole/resolver.ts
  server/src/controllers/Users/resolver.ts
  server/src/util/chapterAdministrator.ts
  server/src/util/chapterBans.ts
  server/tests/chapterAdministrator.test.ts
  server/tests/chapterBans.test.ts
  server/tests/fixtures/chapterUsers.ts
Labels: API

#1833 feat: highlight logged in user
  client/src/components/UserName.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Users/pages/UsersPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/modules/home/index.tsx
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/e2e/dashboard/events/[eventId].cy.ts
Labels: UI/UX

#1835 refactor: avatar component
  client/src/components/Avatar.tsx
  client/src/components/PageLayout/Header.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: status: ready for review

#1836 chore: use getNameText in profile
  client/src/modules/profiles/pages/userProfile.tsx
Labels: status: ready for review

#1841 fix: function component cannot be given refs
  client/src/components/Avatar.tsx
Labels: status: ready for review

#1851 fix(ui): Inconsistent Header Height
  client/src/components/PageLayout/Header.tsx
Labels: UI/UX, status: ready for review

#1855 feat: create test and banned member commands
  package.json
Labels: status: ready for review

#1863 fix: inconsistent share button size in eventPage
  client/src/components/SharePopOver.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
Labels: status: ready for review

#1865 fix(gitpod): nc command is missing
  .gitpod.yml
Labels: status: ready for review

#1848 feat: polish the styling for EventCard date
  client/src/components/EventCard.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/events/graphql/queries.ts
  client/src/modules/home/graphql/queries.ts
  client/tests/EventCard.test.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: status: ready for review

#1867 fix: center chapterCards in chaptersPage section
  client/src/components/ChapterCard.tsx
  client/src/modules/chapters/pages/chaptersPage.tsx
Labels: status: ready for review

#1805 fix: check instance role when chapter admin leaves chapter
  cypress/e2e/dashboard/chapters/chapter-administrator.cy.ts
  server/src/controllers/ChapterUser/resolver.ts
Labels: status: ready for review

#1777 feat: don't send event invites if event starts in the past
  client/src/modules/dashboard/Events/components/DatePicker.tsx
  client/src/modules/dashboard/Events/components/EventDatesForm.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
Labels: status: ready for review

#1815 feat: create event in calendar from event dashboard
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/graphql-types/Chapter.ts
  server/src/graphql-types/Event.ts
  server/src/util/calendar.ts
Labels: status: ready for review

#1860 feat: redact secrets
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/util/calendar.ts
  server/src/util/redact-secrets.ts
  server/tests/fixtures/objects-with-secrets.ts
  server/tests/redact-secrets.test.ts
  tsconfig.test.json
Labels: API

#1883 fix: redact secrets inside strings
  server/src/util/redact-secrets.ts
  server/tests/fixtures/objects-with-secrets.ts
  server/tests/redact-secrets.test.ts
Labels: API

#1861 feat: add border to the menu
  client/src/components/PageLayout/Header.tsx
  client/src/components/PageLayout/HeaderMenu.tsx
  client/src/components/PageLayout/component/HeaderContainer.tsx
  client/src/styles/Header.module.css
Labels: status: ready for review

#1868 feat: add google auth in userProfile and Policy
  client/src/modules/dashboard/Calendar/index.ts
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
  client/src/modules/dashboard/shared/components/Layout.tsx
  client/src/modules/policy/pages/policyPage.tsx
  client/src/modules/profiles/pages/userProfile.tsx
  client/src/pages/dashboard/calendar/index.tsx
Labels: status: ready for review

#1904 feat: automatic unsubscribe at cancel RSVP
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1766 feat: dashboards with admined content only
  client/graphql.schema.json
  client/src/components/PageLayout/Header.tsx
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/dashboard/Venues/graphql/queries.ts
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  client/src/modules/dashboard/Venues/utils.ts
  client/src/modules/profiles/pages/userProfile.tsx
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/e2e/dashboard/venues.cy.ts
  cypress/support/commands.ts
  cypress/support/util.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/User/resolver.ts
  server/src/controllers/Venue/resolver.ts
  server/src/util/adminedChapters.ts
Labels: status: ready for review

#1913 fix: url param name
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1882 feat: polish dashboard eventsPage's event status
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
Labels: status: ready for review

#1915 fix: consistent layout for dashboard
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
  client/src/modules/dashboard/Users/pages/UsersPage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
Labels: status: merge conflict

#1931 fix: refetch dashboard event
  client/src/modules/dashboard/Events/components/Actions.tsx
Labels: status: ready for review

#1930 fix: <a> cannot appear as a descendant of <a>
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
Labels: status: ready for review

#1928 fix: refetch dashboard chapters
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
Labels: status: ready for review

#1929 fix: rename special prop
  client/src/modules/dashboard/Events/components/DatePicker.tsx
  client/src/modules/dashboard/Events/components/EventDatesForm.tsx
Labels: status: ready for review

#1921 feat: consistent date display
  client/src/components/EventCard.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: status: ready for review

#1918 chore: remove init script
  .github/workflows/ci-workflow.yaml
  .github/workflows/do-reset-dev-db.yml
  .gitpod.yml
  common/roles.ts
  cypress.config.ts
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  package.json
  server/package.json
  server/prisma/init/factories/chapterRoles.factory.ts
  server/prisma/init/factories/eventRoles.factory.ts
  server/prisma/init/factories/instanceRoles.factory.ts
  server/prisma/init/factories/rsvpTypes.factory.ts
  server/prisma/init/init.ts
  server/prisma/migrations/20221117104025_seed_permissions_and_rsvps/migration.sql
  server/prisma/seed/factories/rsvps.factory.ts
  server/prisma/seed/factories/user.factory.ts
  server/prisma/seed/seed.ts
  server/prisma/seed/setupRoles.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/InstanceRole/resolver.ts
  server/src/controllers/Users/resolver.ts
  server/src/util/chapterAdministrator.ts
  server/src/util/chapterBans.ts
  server/tests/chapterAdministrator.test.ts
  server/tests/chapterBans.test.ts
  server/tests/fixtures/chapterUsers.ts
Labels: status: ready for review

#1899 fix: redact serialized objects
  server/src/util/redact-secrets.ts
  server/tests/redact-secrets.test.ts
Labels: API

#1940 fix: wrong data type in link component
  client/src/components/ChapterCard.tsx
Labels: status: ready for review

#1916 feat: mention email in userProfile
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/profiles/graphql/queries.ts
  client/src/modules/profiles/pages/userProfile.tsx
  server/src/controllers/User/resolver.ts
  server/src/graphql-types/User.ts
Labels: status: ready for review

#1945 refactor: remove unused email modal
  client/src/modules/dashboard/Events/components/SendEmailModal.tsx
Labels: UI/UX

#1920 feat: log in when confirming RSVP
  client/src/hooks/useAuth.ts
  client/src/modules/events/pages/eventPage.tsx
  client/src/pages/_app.tsx
Labels: status: ready for review

#1891 feat: chapter permissions check in client
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/auth/graphql/queries.ts
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/graphql/mutations.ts
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/util/check-permission.ts
  common/authorization.ts
  common/permissions.ts
  cypress/support/commands.ts
  server/prisma/migrations/20221123213911_add_UsersView_to_chapter_permissions/migration.sql
  server/src/app.ts
  server/src/authorization/index.ts
  server/src/controllers/Auth/middleware.ts
  server/src/controllers/Auth/resolver.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/User/resolver.ts
  server/src/controllers/Users/resolver.ts
  server/src/graphql-types/Chapter.ts
  server/src/graphql-types/ChapterUser.ts
  server/src/graphql-types/Event.ts
  server/src/graphql-types/EventUser.ts
  server/src/graphql-types/User.ts
  server/src/graphql-types/UserBan.ts
Labels: status: ready for review

#1955 feat: filtering the event date in home page
  client/src/modules/home/index.tsx
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1958 feat: hide chapters, events and venues dashboard from members
  client/src/components/PageLayout/Header.tsx
  common/permissions.ts
  cypress/e2e/dashboard/pages-needing-permission.cy.ts
  cypress/e2e/universal-components/menu.cy.ts
  server/prisma/migrations/20221124155109_add_dashboard_view_permissions/migration.sql
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Venue/resolver.ts
Labels: UI/UX

#1963 feat: hide dashboard buttons in eventpage and chapterpage
  client/src/modules/chapters/pages/chaptersPage.tsx
  client/src/modules/events/pages/eventsPage.tsx
Labels: status: ready for review

#1960 feat: filter event in chapterCard
  server/src/controllers/Chapter/resolver.ts
Labels: status: ready for review

#1956 fix: administrators abusing their permissions
  common/authorization.ts
  server/tests/authorization.test.ts
  server/tests/fixtures/users.ts
Labels: API

#1967 feat: delete redundant file
  client/src/util/sanitizeFormData.ts
Labels: status: ready for review

#1976 chore: update resolver name
  server/src/controllers/User/resolver.ts
  server/src/controllers/index.ts
Labels: status: ready for review

#1951 feat: add footer carrying chapter policy
  client/src/components/PageLayout/component/Footer.tsx
  client/src/components/PageLayout/index.tsx
  client/src/modules/policy/pages/policyPage.tsx
Labels: status: ready for review

#1517 chore: cancel event email content
  server/src/controllers/Events/resolver.ts
  server/src/util/eventEmail.ts
Labels: status: ready for review

#1983 feat: indicate if event is canceled in eventPage
  client/src/modules/events/pages/eventPage.tsx
Labels: status: ready for review

#1922 feat: polish Chapter Card layout
  client/graphql.schema.json
  client/src/components/ChapterCard.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/home/graphql/queries.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/graphql-types/Chapter.ts
Labels: status: ready for review

#1972 fix: outline issues in the navbar
  client/src/components/PageLayout/Header.tsx
Labels: status: ready for review

#1974 fix: outline issue in Calendar dashboard
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
Labels: status: ready for review

#2002 feat: move the Alert from the main content section
  client/src/components/PageLayout/index.tsx
Labels: status: ready for review
