Repository freeCodeCamp/chapter, pull requests merged in 2022-12, with the labels that each got.

#1973 fix: outline issues in chapterCard and EventCard
  client/src/components/ChapterCard.tsx
  client/src/components/EventCard.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: status: ready for review

#1987 feat: remove misused headings in chapterPage
  client/src/modules/chapters/pages/chapterPage.tsx
Labels: status: ready for review

#1990 fix: rsvp to rsvped event
  client/src/modules/events/pages/eventPage.tsx
Labels: Bug, UI/UX, status: ready for review

#2022 refactor: rsvpStatus actions logic
  client/src/modules/events/pages/eventPage.tsx
Labels: UI/UX, status: ready for review

#2030 feat: remove auth with google from policy page
  client/src/modules/policy/pages/policyPage.tsx
Labels: status: ready for review

#2033 feat: mention the command that creates seed.js
  CONTRIBUTING.md
Labels: status: ready for review

#1991 feat: add screen reader text in chapterDashboardPage
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
Labels: status: ready for review, a11y

#1979 fix: screen reader reading extra content in menuItem
  client/src/components/PageLayout/Header.tsx
Labels: status: ready for review, a11y

#2026 feat: add text in eventsPage for screen reader and voice user
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
Labels: status: ready for review, a11y

#2024 feat: add text in chapterUser for screen reader and voice users
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  cypress/e2e/dashboard/chapters/users.cy.ts
Labels: status: ready for review, a11y

#1966 feat: send email when event data changes
  cypress/e2e/dashboard/events/events-index.cy.ts
  server/src/controllers/Events/resolver.ts
  server/src/util/date.ts
Labels: API, status: ready for review

#2025 feat: add text in eventPage for screent reader and voice user
  client/src/modules/dashboard/Events/pages/EventPage.tsx
Labels: status: ready for review, a11y

#1942 feat: create a download user data button
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/profiles/graphql/queries.ts
  client/src/modules/profiles/pages/userProfile.tsx
  server/src/controllers/User/resolver.ts
  server/src/graphql-types/ChapterUser.ts
  server/src/graphql-types/EventUser.ts
  server/src/graphql-types/User.ts
  server/src/graphql-types/UserBan.ts
Labels: status: merge conflict

#2015 fix: stop new rsvps cancelling attendance
  server/src/app.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/services/Google.ts
  server/src/services/InitGoogle.ts
  server/src/util/calendar.ts
  server/tests/google.test.ts
Labels: API

#2023 feat: turn the user image in nav into a menu
  client/src/components/PageLayout/Header.tsx
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: UI/UX, status: needs update

#2050 fix: outline for blue buttons
  client/src/styles/ButtonOutline.ts
  client/src/styles/themes.ts
Labels: UI/UX, status: ready for review, a11y

#2064 feat: use semantic html and update footer content
  client/src/components/PageLayout/component/Footer.tsx
  client/src/components/PageLayout/index.tsx
Labels: status: ready for review

#2057 fix: heading structure on events page
  client/src/components/EventCard.tsx
  client/src/modules/events/pages/eventsPage.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: status: ready for review

#2068 feat: email user for change in chapter role
  server/src/controllers/ChapterUser/resolver.ts
Labels: API, status: ready for review

#2074 fix(calendar): use the minimal number of scopes
  server/src/services/InitGoogle.ts
Labels: API

#2075 fix: make new chapters available for new events
  client/src/modules/dashboard/Chapters/index.ts
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewEventForChapterPage.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/pages/dashboard/chapters/[id]/new-event.tsx
Labels: Bug, UI/UX

#2076 fix: set token as valid when updating it
  server/src/services/InitGoogle.ts
Labels: API, status: ready for review

#2038 Feat: send an email about instances roles changes
  cypress/e2e/dashboard/users.cy.ts
  server/src/controllers/Users/resolver.ts
Labels: API

#2081 feat: add focus outline to Button
  client/src/styles/ButtonOutline.ts
Labels: status: ready for review, a11y

#2090 feat: add delete chapter button to edit page
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Chapters/components/DeleteChapterButton.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
Labels: UI/UX

#2078 feat: optionally attend events you create
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/support/commands.ts
  server/src/controllers/Events/resolver.ts
Labels: UI/UX, API

#2084 feat: added RSVP functionality for logged out users when using the ask_to_confirm query param
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/events/pages/eventPage.tsx
  cypress/e2e/events/[eventId].cy.ts
  server/src/controllers/Events/resolver.ts
  server/tests/Mailer.test.ts
Labels: UI/UX, status: ready for review

#2083 feat: token invalidation
  server/src/services/Google.ts
  server/src/services/InitGoogle.ts
  server/src/util/calendar.ts
Labels: API

#2095 fix: use openssl1.1-compat to let prisma generate
  client.Dockerfile
  server.Dockerfile
Labels: status: blocked

#2096 fix: bound cache to prevent DoS
  server/src/app.ts
Labels: API

#2100 fix: disambiguation invitation and confirmation
  server/src/controllers/Events/resolver.ts
Labels: Email

#2091 chore: refactor MailerService
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  server/reminders/reminders.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Messages/inputs.ts
  server/src/controllers/Messages/resolver.ts
  server/src/controllers/Users/resolver.ts
  server/src/controllers/index.ts
  server/src/services/MailerService.ts
  server/src/util/calendar.ts
  server/tests/Mailer.test.ts
  server/tests/Resolver.test.ts
Labels: API, Email

#2102 chore: remove unused arg from sendEventInvite
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/graphql/mutations.ts
  cypress/support/commands.ts
  server/src/controllers/Events/resolver.ts
Labels: API

#2114 fix: remove no longer used argument
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#2101 feat: removing iCalendar from invitations
  package-lock.json
  server/package.json
  server/src/controllers/Events/resolver.ts
  server/src/services/MailerService.ts
Labels: Email

#2103 feat: enable auto_subscribe by default
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/profiles/component/ProfileForm.tsx
  cypress.config.ts
  cypress/e2e/chapters/[chapterId].cy.ts
  cypress/e2e/profile.cy.ts
  server/prisma/migrations/20221215172150_auto_subscribe_by_default/migration.sql
  server/prisma/schema.prisma
Labels: UI/UX, API, status: ready for review

#2125 fix: no confirmation if user is already rsvp'd
  client/src/modules/events/pages/eventPage.tsx
Labels: UI/UX, status: ready for review

#2137 feat: even chapter buttons
  client/src/modules/chapters/pages/chapterPage.tsx
Labels: UI/UX

#2139 feat: add isLoading to action buttons
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: UI/UX

#2115 feat: don't update calendar attendees for events in the past
  server/src/controllers/Events/resolver.ts
  server/src/services/Google.ts
  server/tests/google.test.ts
Labels: API, status: ready for review

#2143 feat: display only events from venue
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  server/src/controllers/Venue/resolver.ts
Labels: UI/UX, API

#2145 feat: add message for no events
  client/src/modules/dashboard/shared/components/EventList.tsx
Labels: UI/UX

#2150 feat: add colors to token statuses
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
Labels: UI/UX
