Repository freeCodeCamp/chapter, pull requests merged in 2022-07, with the labels that each got.

#1136 feat(auth): restrict chapter edits
  cypress/e2e/dashboard/chapters/[chapterId]/edit.cy.js
  cypress/e2e/dashboard/chapters/[chapterId]/index.cy.js
  cypress/e2e/dashboard/chapters/index.cy.js
  cypress/e2e/dashboard/events/index.cy.js
  cypress/support/commands.js
  server/src/controllers/Chapter/resolver.ts
Labels: status: ready for review

#1158 feat: restrict confirm/kick of RSVPs
  cypress/e2e/dashboard/events/[eventId].cy.js
  cypress/support/commands.js
  server/prisma/generator/factories/chapterRoles.factory.ts
  server/prisma/generator/factories/instanceRoles.factory.ts
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#1145 refactor: stronger types for permissions
  server/prisma/generator/factories/chapterRoles.factory.ts
  server/prisma/generator/factories/instanceRoles.factory.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Users/resolver.ts
Labels: status: ready for review

#1187 feat: restrict sponsors management
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx
  client/src/modules/dashboard/shared/components/Layout.tsx
  cypress/e2e/dashboard/sponsors.cy.js
  cypress/support/commands.js
  cypress/support/index.d.ts
  server/prisma/generator/factories/instanceRoles.factory.ts
  server/src/controllers/Sponsors/resolver.ts
Labels: status: ready for review

#1160 feat: restrict event creation
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  cypress/e2e/dashboard/chapters/[chapterId]/index.cy.js
  cypress/e2e/dashboard/events/index.cy.js
  cypress/plugins/index.js
  cypress/support/commands.js
  server/prisma/generator/setupRoles.ts
  server/src/controllers/Events/inputs.ts
  server/src/controllers/Events/resolver.ts
Labels: API, status: ready for review

#1190 refactor: move permissions to common module
  .gitignore
  client.Dockerfile
  client/next.config.js
  client/src/hooks/useCheckPermission.ts
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/shared/components/Layout.tsx
  client/tsconfig.json
  common/permissions.ts
  server.Dockerfile
  server/prisma/generator/factories/chapterRoles.factory.ts
  server/prisma/generator/factories/instanceRoles.factory.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Sponsors/resolver.ts
  server/src/controllers/Users/resolver.ts
  server/tsconfig.json
Labels: status: ready for review

#1200 refactor: gqlOptions helper
  cypress.config.ts
  cypress/e2e/auth/login.cy.js
  cypress/e2e/dashboard/events/[eventId].cy.js
  cypress/support/commands.js
  cypress/support/util.js
Labels: status: ready for review

#1194 refactor: replace rejectOnNotFound
  cypress/e2e/events/[eventId].cy.js
  server/prisma/generator/factories/rsvps.factory.ts
  server/src/controllers/Auth/middleware.ts
  server/src/controllers/Auth/resolver.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/EventUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/prisma.ts
Labels: status: ready for review

#1186 feat: restrict sub/unsub from event
  common/permissions.ts
  cypress/e2e/events/[eventId].cy.js
  cypress/support/commands.js
  cypress/support/index.d.ts
  server/prisma/generator/factories/chapterRoles.factory.ts
  server/src/controllers/EventUser/resolver.ts
Labels: status: ready for review

#1212 feat: restrict venue creation
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Venues/components/VenueForm.tsx
  client/src/modules/dashboard/Venues/graphql/mutations.ts
  client/src/modules/dashboard/Venues/graphql/queries.ts
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  client/src/modules/dashboard/shared/components/Layout.tsx
  client/src/pages/dashboard/chapters/[id]/new-venue.tsx
  client/src/pages/dashboard/chapters/[id]/venues/[venueId]/edit.tsx
  client/src/pages/dashboard/venues/[id]/edit.tsx
  client/src/pages/dashboard/venues/new.tsx
  common/permissions.ts
  cypress/e2e/dashboard/venues.cy.js
  cypress/support/commands.js
  cypress/support/index.d.ts
  server/prisma/generator/factories/venues.factory.ts
  server/prisma/generator/seed.ts
  server/prisma/schema.prisma
  server/src/controllers/Venue/resolver.ts
  server/src/graphql-types/Venue.ts
Labels: UI/UX, API, status: ready for review

#1226 docs(contributing): moved running remotely to env config
  CONTRIBUTING.md
Labels: Documentation, status: ready for review

#1227 docs: Add WSL + Docker errors to the Troubleshooting and Improve Windows / WSL Notes
  CONTRIBUTING.md
Labels: Documentation, status: ready for review

#1004 feat: unsubscribe link
  .env.example
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/unsubscribe/graphql/mutations.ts
  client/src/modules/unsubscribe/index.tsx
  client/src/pages/unsubscribe/index.tsx
  cypress/e2e/dashboard/chapters/[chapterId]/index.cy.js
  cypress/e2e/dashboard/events/index.cy.js
  cypress/e2e/unsubscribe.cy.js
  cypress/support/commands.js
  cypress/support/index.d.ts
  server/reminders/reminders.ts
  server/src/config/index.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Unsubscribe/inputs.ts
  server/src/controllers/Unsubscribe/resolver.ts
  server/src/controllers/index.ts
  server/src/services/MailerService.ts
  server/src/services/UnsubscribeToken.ts
Labels: status: ready for review

#1248 fix: require fields when logging in/registering
  client/src/components/LoginRegisterModal.tsx
  client/src/modules/auth/pages/Login.tsx
  client/src/modules/auth/pages/Register.tsx
Labels: status: ready for review

#1203 feat: add pagination to event-feed page
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/events/graphql/queries.ts
  client/src/modules/events/pages/eventsPage.tsx
  cypress/e2e/events/events-index.cy.ts
  server/src/controllers/Events/resolver.ts
  server/src/graphql-types/Event.ts
Labels: UI/UX

#1265 feat: add chapter actions to chapters dashboard
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
Labels: status: ready for review

#1277 fix: change magic link to include client location
  .gitpod.yml
  server/src/controllers/Auth/resolver.ts
Labels: status: ready for review

#1276 Added margin bottom for buttons on EventForm
  client/src/modules/dashboard/Events/components/EventForm.tsx
Labels: status: needs update

#1285 chore: rename permissions
  common/permissions.ts
  server/src/controllers/Users/resolver.ts
Labels: status: ready for review

#1289 chore: don't skip CI checks when adding contributors
  .all-contributorsrc
Labels: status: ready for review

#1284 feat: authorize chapter user role change
  common/permissions.ts
  cypress/e2e/dashboard/chapters/users.cy.ts
  cypress/support/commands.ts
  server/src/controllers/ChapterUser/resolver.ts
Labels: status: ready for review

#1264 feat: augment chapter - venue relation
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Venues/components/VenueForm.tsx
  client/src/modules/dashboard/Venues/graphql/queries.ts
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  server/prisma/generator/factories/events.factory.ts
  server/prisma/generator/factories/venues.factory.ts
  server/prisma/generator/seed.ts
  server/prisma/schema.prisma
  server/src/controllers/Venue/resolver.ts
  server/src/graphql-types/Venue.ts
Labels: status: ready for review

#1286 docs(README, CONTRIBUTING): added cypress and its usage
  CONTRIBUTING.md
  README.md
Labels: status: ready for review

#1291 fix: infer chapterId from events, not user_events
  server/src/app.ts
  server/src/authorization/index.ts
  server/src/common-types/gql.ts
  server/src/controllers/Auth/middleware.ts
  server/src/controllers/Auth/resolver.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/EventUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/tests/authorization.test.ts
  server/tests/fixtures/events.ts
  server/tests/fixtures/users.ts
Labels: API, status: ready for review

#1280 feat: authorize chapter join subscribe
  common/permissions.ts
  cypress/e2e/chapters/[chapterId].cy.ts
  cypress/support/commands.ts
  server/prisma/generator/factories/instanceRoles.factory.ts
  server/src/controllers/ChapterUser/resolver.ts
Labels: status: ready for review

#1310 feat: added validation for form data edited or not
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
Labels: status: ready for review

#1313 fix: use correct loading to display loading message
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
Labels: status: ready for review
