Repository freeCodeCamp/chapter, pull requests merged in 2023-01, with the labels that each got.

#2159 fix: cypress not selecting correct date
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/fixtures/events.json
Labels: Bug

#2161 fix: select event from home page
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#2167 fix: tidy up invitation text
  server/src/controllers/Events/resolver.ts
  server/src/util/eventEmail.ts
Labels: Email

#2082 feat: ensure refresh_token is obtained when authenticating
  server/src/app.ts
  server/src/services/InitGoogle.ts
Labels: API, status: ready for review

#2140 feat: improve events list ux in dashboard
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/components/DeleteChapterButton.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  server/src/controllers/Events/resolver.ts
Labels: UI/UX, API, status: ready for review

#2173 fix: overflow dashboard links
  client/src/modules/dashboard/shared/components/Layout.tsx
Labels: UI/UX, status: ready for review

#2174 feat: change gitpod 3000 port to notify onOpen
  .gitpod.yml
Labels: status: ready for review, config

#2136 feat: improve calendar event creation ux
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
Labels: UI/UX, status: ready for review

#2179 feat: remove the limit with event with venues
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  server/src/controllers/Events/resolver.ts
Labels: API, status: ready for review

#2176 feat: indicate ability to scroll dashboard links
  client/src/modules/dashboard/shared/components/Layout.tsx
Labels: UI/UX, status: ready for review

#2127 feat: limit number of events in the chapterCard
  client/src/components/ChapterCard.tsx
  server/src/controllers/Chapter/resolver.ts
Labels: API, status: ready for review

#2134 feat: create calendar from chapter dashboard
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/graphql/mutations.ts
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  server/src/controllers/Chapter/resolver.ts
Labels: UI/UX, API, status: ready for review

#2183 test: RSVPing to invite only event
  cypress.config.ts
  cypress/e2e/events/[eventId].cy.ts
Labels: status: ready for review

#2193 feat: change eventForm CTA buttons to grid
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
Labels: UI/UX, status: ready for review

#2191 feat: display chapter logo in chapter card and page
  client/src/components/ChapterCard.tsx
  client/src/modules/chapters/pages/chapterPage.tsx
Labels: UI/UX, status: ready for review

#2181 fix: only create sessions after authenticating
  client/src/components/PageLayout/Header.tsx
  client/src/components/PageLayout/index.tsx
  client/src/components/UserName.tsx
  client/src/hooks/useAuth.ts
  client/src/hooks/useSession.ts
  client/src/modules/auth/context.tsx
  client/src/modules/auth/providers/auth0.tsx
  client/src/modules/auth/providers/common-context.tsx
  client/src/modules/auth/providers/dev.tsx
  client/src/modules/auth/user.tsx
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/chapters/pages/chaptersPage.tsx
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/components/DeleteChapterButton.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventChapterSelect.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Sponsors/pages/NewSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
  client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  client/src/modules/dashboard/shared/components/Layout.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/modules/events/pages/eventsPage.tsx
  client/src/modules/home/index.tsx
  client/src/modules/policy/pages/policyPage.tsx
  client/src/modules/profiles/pages/userProfile.tsx
  client/src/pages/_app.tsx
  client/src/util/check-permission.ts
  cypress/support/commands.ts
Labels: UI/UX

#2202 feat: add freeCodeCamp tos and code of conduct
  client/src/components/PageLayout/component/Footer.tsx
  client/src/modules/policy/index.ts
  client/src/modules/policy/pages/policyPage.tsx
  client/src/pages/policy/index.tsx
Labels: status: ready for review

#2190 feat: refactor userProfile form submit
  client/src/modules/profiles/component/ProfileForm.tsx
Labels: UI/UX, status: ready for review

#2152 feat: test saved tokens
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Calendar/graphql/mutations.ts
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
  server/src/controllers/Calendar/resolver.ts
  server/src/services/Google.ts
  server/src/services/InitGoogle.ts
Labels: UI/UX, API, status: ready for review

#2212 fix: prevent double next calls in user middleware
  server/src/controllers/Auth/middleware.ts
Labels: Bug, API

#2225 chore: query chapter venues after chapterId is available
  client/src/modules/dashboard/Events/components/EventForm.tsx
Labels: status: ready for review

#2221 refactor: rename layout to dashboardLayout
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/NewSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
  client/src/modules/dashboard/Users/pages/UsersPage.tsx
  client/src/modules/dashboard/Venues/pages/ChapterNewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  client/src/modules/dashboard/shared/components/DashboardLayout.tsx
  client/src/pages/dashboard/index.tsx
Labels: status: ready for review

#2241 fix: Popper console warning on Menu click
  client/src/components/PageLayout/Header.tsx
Labels: status: ready for review

#2248 fix: logo image being in the center of chaptersPage
  client/src/modules/chapters/pages/chaptersPage.tsx
Labels: UI/UX, status: ready for review

#2253 fix: ensure switch state before unchecking
  cypress/e2e/profile.cy.ts
Labels: status: ready for review

#2251 fix: refetch query for individual item
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Venues/graphql/queries.ts
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
Labels: UI/UX, status: ready for review

#2249 chore: remove unused component
  client/src/components/Form/Fields.tsx
Labels: status: ready for review

#2252 refactor: userProfile loading
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/profiles/pages/userProfile.tsx
  server/src/controllers/User/resolver.ts
Labels: UI/UX, status: ready for review

#2247 refactor: move email providers into own classes
  server/src/services/MailerService.ts
  server/src/services/mail-providers/abstract-provider.ts
  server/src/services/mail-providers/sendgrid.ts
  server/src/services/mail-providers/ses.ts
  server/src/services/mail-providers/smtp-helpers.ts
  server/src/services/mail-providers/smtp.ts
  server/src/util/Utilities.ts
  server/tests/MailerProvider.test.ts
  server/tests/Utilities.test.ts
  server/tests/smtp-helpers.test.ts
Labels: Email

#2234 feat: add chapter link to dashboard pages
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
Labels: UI/UX, status: ready for review

#2257 fix: limit unhelpful errors
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Unsubscribe/resolver.ts
  server/src/util/eventEmail.ts
Labels: UI/UX, API, status: ready for review

#2258 fix: always display loading error
  client/src/components/Loading.tsx
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/chapters/pages/chaptersPage.tsx
  client/src/modules/dashboard/shared/components/DashboardLayout.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/modules/events/pages/eventsPage.tsx
  client/src/modules/home/index.tsx
  client/src/modules/profiles/pages/userProfile.tsx
Labels: UI/UX, status: ready for review

#2261 fix: find events/venues with user.id in auth
  server/src/controllers/Auth/middleware.ts
Labels: API

#2238 feat: meet creation/removal based on venue_type
  server/src/controllers/Events/resolver.ts
  server/src/services/Google.ts
  server/src/util/calendar.ts
  server/src/util/venue.ts
  server/tests/google.test.ts
Labels: API, status: ready for review

#2260 feat: retry requests on network errors
  client/src/pages/_app.tsx
Labels: status: ready for review

#2263 fix: only require chrome users to logout once
  client/src/hooks/useSession.ts
  client/src/modules/auth/user.tsx
Labels: API

#2077 fix: remove link when authenticated
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
Labels: UI/UX, status: ready for review

#2245 fix: form validations
  client/src/components/Form/Input.tsx
  client/src/components/Form/TextArea.tsx
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/util/form.ts
Labels: UI/UX, status: ready for review

#2268 fix: make users-view just an instance permission again
  client/src/components/PageLayout/Header.tsx
  client/src/components/PageLayout/index.tsx
  client/src/modules/chapters/pages/chaptersPage.tsx
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/components/DeleteChapterButton.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Sponsors/pages/NewSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
  client/src/modules/dashboard/shared/components/DashboardLayout.tsx
  client/src/modules/events/pages/eventsPage.tsx
  client/src/util/check-permission.ts
  common/permissions.ts
  server/prisma/migrations/20230124093945_remove_users_view_from_chapter_permissions/migration.sql
Labels: Bug

#2284 chore: replace rsvp with attend
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/e2e/events/[eventId].cy.ts
  cypress/e2e/profile.cy.ts
  server/src/controllers/Events/resolver.ts
Labels: UI/UX

#2286 feat: integration info during chapter creation
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
Labels: UI/UX, status: ready for review

#2291 fix: sort by name
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Sponsors/resolver.ts
Labels: API, status: ready for review

#2293 chore: instance authentication wording
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
Labels: UI/UX, status: ready for review

#2277 feat: unlink chapter calendar
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/graphql/mutations.ts
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  server/src/controllers/Chapter/resolver.ts
  server/src/services/Google.ts
Labels: UI/UX, API, status: ready for review

#2300 fix: tidy up some wording on the chapter page
  client/src/modules/chapters/pages/chapterPage.tsx
  cypress/e2e/chapters/[chapterId].cy.ts
Labels: UI/UX

#2302 fix: admined_chapters order
  server/src/controllers/User/resolver.ts
Labels: API, status: ready for review

#2306 feat: fixed Individual chapter dashboards link to the dashboards for their events
  client/src/modules/dashboard/shared/components/EventList.tsx
Labels: UI/UX, status: ready for review

#2311 fix: loadingUser stuck on error
  client/src/components/PageLayout/Header.tsx
  client/src/hooks/useSession.ts
  client/src/modules/auth/user.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: UI/UX, status: ready for review
