Repository freeCodeCamp/chapter, pull requests merged in 2023-03, with the labels that each got.

#2430 chore: add joined_date field to event_users
  server/prisma/migrations/20230301175317_add_joined_date_to_event_users/migration.sql
  server/prisma/schema.prisma
Labels: API, status: ready for review

#2340 feat: add total to paginatedPage and clear the extra queries
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/components/DeleteChapterButton.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/events/graphql/queries.ts
  client/src/modules/events/pages/eventsPage.tsx
  client/src/modules/home/graphql/queries.ts
  client/src/modules/home/index.tsx
  client/src/modules/util/pagination.tsx
  client/src/pages/_app.tsx
  cypress/e2e/events/events-index.cy.ts
  server/src/controllers/Events/resolver.ts
  server/src/graphql-types/Event.ts
Labels: UI/UX, API, status: ready for review

#2420 chore: replace toast with alert
  client/src/components/Alerts/AlertContext.tsx
  client/src/components/Alerts/AlertProvider.tsx
  client/src/components/Alerts/Alerts.tsx
  client/src/components/PageLayout/Header.tsx
  client/src/components/PageLayout/index.tsx
  client/src/hooks/useAlert.ts
  client/src/hooks/useDisableWhileSubmitting.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/NewSponsorPage.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/utils.ts
  client/src/modules/events/pages/eventPage.tsx
  client/src/modules/profiles/pages/userProfile.tsx
  client/src/pages/_app.tsx
Labels: UI/UX, status: ready for review

#2435 feat: check if capacity isn't below number of confirmed attendees
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/util/form.ts
  server/src/controllers/Events/inputs.ts
  server/src/controllers/Events/resolver.ts
Labels: UI/UX, API, status: ready for review

#2439 feat: disable Click for more when fetching more
  client/src/modules/util/pagination.tsx
Labels: UI/UX, status: ready for review

#2434 feat: lazy load the chapters
  client/src/modules/home/index.tsx
Labels: status: ready for review

#2445 chore: seed https images
  server/prisma/seed/factories/chapters.factory.ts
  server/prisma/seed/factories/events.factory.ts
Labels: API, status: ready for review

#2443 fix: ChapterCard displays past events after visiting chapter page
  client/graphql.schema.json
  client/src/components/ChapterCard.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/tests/__snapshots__/ChapterCard.test.tsx.snap
  server/src/controllers/Chapter/resolver.ts
Labels: UI/UX, API, status: ready for review

#2452 chore: improve event dashboard modals wording
  client/src/components/SharePopOver.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: UI/UX, status: ready for review

#2456 feat: move attendee to waitlist
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/support/commands.ts
  server/src/controllers/Events/resolver.ts
  server/src/email-templates.ts
  server/src/util/event-email.ts
  server/tests/event-email.test.ts
Labels: UI/UX, API, status: ready for review

#2352 feat: add fieldset and legend in eventForm for screen readers
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
Labels: status: ready for review

#2463 chore: add AttendanceNames enum
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  common/attendance.ts
  server/prisma/seed/factories/attendance.factory.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Venue/resolver.ts
  server/src/util/waitlist.ts
Labels: status: ready for review

#2464 chore: add grid to event actions on eventPage
  client/src/modules/events/pages/eventPage.tsx
  cypress/e2e/events/[eventId].cy.ts
Labels: UI/UX, status: ready for review

#2465 feat: add fieldset for the checkboxes input
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/unsubscribe/index.tsx
Labels: status: ready for review

#2472 feat: add icon to filter field
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
Labels: UI/UX, status: ready for review

#2480 fix: update chapterPage after login
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/auth/graphql/queries.ts
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  server/src/controllers/ChapterUser/resolver.ts
Labels: UI/UX, status: ready for review

#2371 feat: warn when calendar or calendar event wasn't created
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/auth/graphql/queries.ts
  client/src/modules/dashboard/Chapters/graphql/mutations.ts
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/graphql-types/Event.ts
Labels: UI/UX, status: ready for review

#2487 fix: add checks for success message
  cypress/e2e/chapters/[chapterId].cy.ts
Labels: status: ready for review

#2492 fix: use AttendanceNames enum
  server/src/util/waitlist.ts
Labels: API, status: ready for review

#2479 feat: chapter subscription opt-in
  client/graphql.schema.json
  client/src/components/SubscribeCheckbox.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/mutations.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  cypress/e2e/chapters/[chapterId].cy.ts
  server/src/controllers/ChapterUser/resolver.ts
Labels: UI/UX, API, status: ready for review

#2496 chore: display event url
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/events/pages/eventPage.tsx
Labels: UI/UX, status: ready for review

#2500 fix: Add space between event image and header using PageLayout
  client/src/components/PageLayout/index.tsx
Labels: UI/UX, status: ready for review

#2501 fix: .all-contributorsrc json
  .all-contributorsrc
Labels: status: ready for review

#2506 fix: <a> cannot appear as descendant of <a>
  client/src/modules/events/pages/eventPage.tsx
Labels: status: ready for review

#2517 fix: use ChapterRoles enum
  client/src/modules/chapters/pages/chapterPage.tsx
Labels: status: ready for review

#2518 fix: grid positioning
  client/src/modules/events/pages/eventPage.tsx
Labels: UI/UX, status: ready for review

#2516 chore: use permission to find chapter admin
  server/src/controllers/Events/resolver.ts
Labels: API, status: ready for review

#2535 feat: add link to edit
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
Labels: UI/UX, status: ready for review

#2519 feat: added venue data to confirmation emails
  server/src/controllers/Events/resolver.ts
  server/src/email-templates.ts
  server/src/util/event-email.ts
  server/tests/event-email.test.ts
Labels: status: ready for review
