Repository freeCodeCamp/chapter, pull requests merged in 2023-06, with the labels that each got.

#2604 fix: don't display zero
  client/src/modules/dashboard/Calendar/pages/Calendar.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
Labels: UI/UX, status: ready for review

#2601 feat: event transfer
  client/src/hooks/useCancelEvent.ts
  client/src/hooks/useCreateEvent.ts
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/components/EventChapterSelect.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  client/src/modules/dashboard/Events/pages/TransferEventPage.tsx
  client/src/pages/dashboard/events/[id]/transfer.tsx
  cypress/e2e/dashboard/events/[eventId].cy.ts
Labels: status: ready for review

#2595 fix: don't include banned chapters in admined_chapters
  server/src/util/adminedChapters.ts
Labels: API, status: ready for review

#2390 feat: delete the test site alert from the pages
  client/src/components/PageLayout/index.tsx
Labels: status: blocked

#2121 feat: hide interaction action elements in dashboard
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Users/pages/UsersPage.tsx
  client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
  client/src/modules/dashboard/shared/components/DashboardLayout.tsx
  cypress/e2e/dashboard/dashboard-index.cy.ts
Labels: UI/UX, status: ready for review

#2526 feat: bring tags back
  client/graphql.schema.json
  client/src/components/ChapterCard.tsx
  client/src/components/EventCard.tsx
  client/src/components/TagsBox.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Chapters/components/ChapterFormUtils.tsx
  client/src/modules/dashboard/Chapters/graphql/mutations.ts
  client/src/modules/dashboard/Chapters/graphql/queries.ts
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/dashboard/Venues/components/VenueFormUtils.tsx
  client/src/modules/dashboard/Venues/graphql/queries.ts
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  client/src/modules/dashboard/Venues/utils.ts
  client/src/modules/events/graphql/queries.ts
  client/src/modules/events/pages/eventPage.tsx
  client/src/util/tags.ts
  client/tests/ChapterCard.test.tsx
  client/tests/EventCard.test.tsx
  client/tests/__snapshots__/ChapterCard.test.tsx.snap
  client/tests/__snapshots__/EventCard.test.tsx.snap
  client/tests/tags.test.ts
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/chapters/[chapterId]/edit.cy.ts
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
  cypress/e2e/dashboard/venues.cy.ts
  cypress/fixtures/chapters.json
  cypress/fixtures/events.json
  cypress/fixtures/venues.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  server/prisma/migrations/20230328184907_add_tags/migration.sql
  server/prisma/schema.prisma
  server/prisma/seed/factories/chapters.factory.ts
  server/prisma/seed/factories/events.factory.ts
  server/prisma/seed/factories/venues.factory.ts
  server/prisma/seed/lib/util.ts
  server/src/controllers/Chapter/inputs.ts
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/inputs.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Venue/inputs.ts
  server/src/controllers/Venue/resolver.ts
  server/src/graphql-types/Chapter.ts
  server/src/graphql-types/Event.ts
  server/src/graphql-types/EventTag.ts
  server/src/graphql-types/Tag.ts
  server/src/graphql-types/Venue.ts
  server/src/graphql-types/index.ts
  server/src/util/tags.ts
  server/tests/tags.test.ts
Labels: UI/UX, API, status: ready for review
