Repository freeCodeCamp/chapter, pull requests merged in 2023-04, with the labels that each got.

#2548 fix: wrap with ChakraProvider in test
  client/tests/ChapterCard.test.tsx
  client/tests/__snapshots__/ChapterCard.test.tsx.snap
Labels: status: ready for review

#2560 refactor: add InfoList component
  client/src/components/InfoList.tsx
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
Labels: status: ready for review

#2490 feat: don't add to calendar when on waitlist
  server/src/controllers/Events/resolver.ts
Labels: API, status: ready for review

#2569 feat: add warning message in case there are people on the waiting list
  client/src/modules/events/components/Actions.tsx
Labels: UI/UX, status: ready for review

#2572 feat: update waitlist on attendee removal
  server/src/controllers/Events/resolver.ts
Labels: status: ready for review

#2571 fix: useMemo dependency
  client/src/modules/events/components/Actions.tsx
Labels: status: ready for review

#2573 feat: indicate invite only in event dashboard
  client/src/modules/dashboard/Events/pages/EventPage.tsx
Labels: UI/UX, status: ready for review

#2563 feat: distinct emails for possible attendances
  server/src/controllers/Events/resolver.ts
  server/src/email-templates.ts
  server/src/util/event-email.ts
  server/tests/event-email.test.ts
Labels: status: ready for review

#2580 feat: send email when off waitlist
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/util/event-email.ts
  server/src/util/waitlist.ts
Labels: API, status: ready for review

#2574 feat: display user joined date in event dashboard
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  server/src/controllers/Events/resolver.ts
  server/src/graphql-types/EventUser.ts
Labels: UI/UX, API, status: ready for review

#2591 refactor: remove local values to global in eventCard
  client/src/components/EventCard.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: status: ready for review

#2588 refactor: split ChapterPage into components
  client/src/modules/dashboard/Chapters/components/Actions.tsx
  client/src/modules/dashboard/Chapters/components/CalendarStatus.tsx
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
Labels: status: ready for review

#2592 refactor: split EventPage into components
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/CalendarEventStatus.tsx
  client/src/modules/dashboard/Events/components/EventUsers.tsx
  client/src/modules/dashboard/Events/components/EventVenue.tsx
  client/src/modules/dashboard/Events/components/Fields.tsx
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/util/getLocationString.ts
Labels: status: ready for review
