Repository freeCodeCamp/chapter, pull requests merged in 2023-02, with the labels that each got.

#2290 feat: add validations with class-validator to `VenueForm` and `ChapterForm`
  client/babel.config.js
  client/package.json
  client/src/components/Form/Form.tsx
  client/src/components/Form/Input.tsx
  client/src/components/Form/Select.tsx
  client/src/components/Form/TextArea.tsx
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Chapters/components/ChapterFormUtils.tsx
  client/src/modules/dashboard/Venues/components/VenueForm.tsx
  client/src/modules/dashboard/Venues/components/VenueFormUtils.tsx
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/utils.ts
  client/src/modules/util/form.ts
  client/tsconfig.json
  package-lock.json
Labels: UI/UX, status: ready for review

#2328 feat(client) : add invite only on chapter card
  client/src/components/ChapterCard.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/home/graphql/queries.ts
Labels: UI/UX, status: ready for review

#2332 fix: delete emails before tests
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/users.cy.ts
Labels: status: ready for review

#2323 feat(client): make events card clickable
  client/src/components/EventCard.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: UI/UX, status: ready for review

#2333 fix: event card image placeholder
  client/src/components/EventCard.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: UI/UX, status: ready for review

#2337 chore: replace rsvp with attendance in db
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/events/graphql/queries.ts
  client/src/modules/events/pages/eventPage.tsx
  client/src/modules/profiles/graphql/queries.ts
  cypress.config.ts
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
  cypress/e2e/events/[eventId].cy.ts
  cypress/support/commands.ts
  server/prisma/migrations/20230203174046_rename_rsvp_table/migration.sql
  server/prisma/schema.prisma
  server/prisma/seed/factories/attendance.factory.ts
  server/prisma/seed/seed.ts
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/User/resolver.ts
  server/src/graphql-types/EventUser.ts
  server/src/graphql-types/Rsvp.ts
  server/src/util/waitlist.ts
Labels: status: ready for review

#2331 feat: add lock icon for invite-only events
  client/src/components/ChapterCard.tsx
  client/src/components/EventCard.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/shared/components/EventList.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: UI/UX, status: ready for review

#2341 chore: server rename rsvp to attend
  CONTRIBUTING.md
  README.md
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Events/graphql/mutations.ts
  client/src/modules/dashboard/Events/pages/EventPage.tsx
  client/src/modules/events/graphql/mutations.ts
  client/src/modules/events/pages/eventPage.tsx
  common/permissions.ts
  cypress/e2e/dashboard/events/[eventId].cy.ts
  cypress/e2e/events/[eventId].cy.ts
  cypress/e2e/profile.cy.ts
  cypress/e2e/unsubscribe.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  server/prisma/migrations/20230205151755_rename_rsvp_permissions/migration.sql
  server/prisma/seed/factories/events.factory.ts
  server/src/controllers/Events/resolver.ts
  server/src/graphql-types/Attendance.ts
  server/src/graphql-types/Event.ts
  server/src/graphql-types/EventUser.ts
  server/src/graphql-types/index.ts
Labels: API, status: ready for review

#2310 feat: form validations for remaining forms
  client/src/components/Form/Select.tsx
  client/src/modules/dashboard/Events/components/DatePicker.tsx
  client/src/modules/dashboard/Events/components/EventChapterSelect.tsx
  client/src/modules/dashboard/Events/components/EventDatesForm.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Events/components/EventFormUtils.ts
  client/src/modules/dashboard/Events/components/EventVenueForm.tsx
  client/src/modules/dashboard/Sponsors/components/SponsorForm.tsx
  client/src/modules/dashboard/Sponsors/components/SponsorFormUtils.tsx
  client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx
  client/src/modules/dashboard/Sponsors/pages/NewSponsorPage.tsx
  client/src/modules/dashboard/Venues/components/VenueForm.tsx
  client/src/modules/dashboard/Venues/components/VenueFormUtils.tsx
  client/src/modules/profiles/component/ProfileForm.tsx
  client/src/modules/profiles/component/ProfileFormUtils.tsx
  client/src/modules/util/form.ts
  cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
  cypress/e2e/dashboard/events/events-index.cy.ts
Labels: status: ready for review

#2349 refactor: add the missing lock icon in dashboard desktop
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
Labels: status: ready for review

#2319 refactor: email text templates
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
  server/src/controllers/Users/resolver.ts
  server/src/email-templates.ts
  server/src/util/calendar.ts
  server/src/util/event-email.ts
  server/src/util/eventEmail.ts
  server/tests/email-templates.test.ts
  server/tests/event-email.test.ts
Labels: API, Email, status: ready for review

#2351 feat: stop the card flashing in eventCard
  client/src/components/EventCard.tsx
  client/tests/__snapshots__/EventCard.test.tsx.snap
Labels: status: ready for review

#2363 fix: prevent the same start_at and ends_at
  server/prisma/seed/factories/events.factory.ts
Labels: API, status: ready for review

#2364 feat: disable button when formState is not valid
  client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
  client/src/modules/dashboard/Events/components/EventForm.tsx
  client/src/modules/dashboard/Sponsors/components/SponsorForm.tsx
  client/src/modules/dashboard/Venues/components/VenueForm.tsx
Labels: UI/UX, status: ready for review

#2365 test: add ChapterCard snapshot
  client/src/components/ChapterCard.tsx
  client/tests/ChapterCard.test.tsx
  client/tests/__snapshots__/ChapterCard.test.tsx.snap
Labels: status: ready for review

#2368 feat: send email after cancelation of attendance
  server/src/controllers/Events/resolver.ts
  server/src/email-templates.ts
  server/src/util/event-email.ts
  server/tests/event-email.test.ts
Labels: API, status: ready for review

#2342 fix: upsert user record during login
  server/src/app.ts
Labels: API, status: ready for review

#2301 feat: add search functionality in chapterDashboard
  client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
Labels: UI/UX, status: ready for review

#2233 feat: move events to TBD venue when deleting venue
  server/src/controllers/Venue/resolver.ts
Labels: API, status: ready for review

#2354 chore: check integrationStatus before trying to use calendar
  server/src/controllers/ChapterUser/resolver.ts
  server/src/controllers/Events/resolver.ts
Labels: API, status: ready for review

#2375 fix(docs): add instructions for making authenticated queries via Apollo Studio
  CONTRIBUTING.md
Labels: Documentation, status: ready for review

#2382 chore: improve attendance status in mobile view
  client/src/modules/dashboard/Events/pages/EventPage.tsx
Labels: UI/UX, status: ready for review

#2381 feat: add specific success text when placed on waitlist
  client/src/generated/graphql.tsx
  client/src/modules/events/graphql/mutations.ts
  client/src/modules/events/pages/eventPage.tsx
Labels: UI/UX, status: ready for review

#2378 fix: seed events with minimum capacity
  server/prisma/seed/factories/events.factory.ts
Labels: status: ready for review

#2285 feat: filter recent dashboard event
  client/graphql.schema.json
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Chapters/components/DeleteChapterButton.tsx
  client/src/modules/dashboard/Events/components/Actions.tsx
  client/src/modules/dashboard/Events/components/EventCancelButton.tsx
  client/src/modules/dashboard/Events/graphql/queries.ts
  client/src/modules/dashboard/Events/pages/EditEventPage.tsx
  client/src/modules/dashboard/Events/pages/EventsPage.tsx
  client/src/modules/dashboard/Events/pages/NewEventPage.tsx
  server/src/controllers/Events/resolver.ts
Labels: UI/UX, status: ready for review

#2192 feat: add delete button for venues
  client/src/generated/graphql.tsx
  client/src/modules/dashboard/Venues/graphql/mutations.ts
  client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx
  client/src/modules/dashboard/Venues/pages/VenuePage.tsx
  server/src/controllers/Venue/resolver.ts
  server/src/email-templates.ts
  server/src/util/event-email.ts
  server/tests/email-templates.test.ts
Labels: UI/UX, API, status: ready for review

#2384 feat(ui): adding link to event page from chapter dashboard
  client/src/modules/dashboard/shared/components/EventList.tsx
Labels: UI/UX

#2396 fix: ensure more consistent events ordering
  server/src/controllers/Chapter/resolver.ts
  server/src/controllers/Events/resolver.ts
Labels: API, status: ready for review

#2397 fix: wait for two mails
  cypress/e2e/events/[eventId].cy.ts
Labels: status: ready for review

#2398 chore: replace url after deletion
  client/src/modules/dashboard/Chapters/components/DeleteChapterButton.tsx
Labels: status: ready for review

#2402 feat: redirect to chapter page and display its content
  client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
  client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
  cypress/e2e/dashboard/chapters/chapters-index.cy.ts
Labels: status: ready for review

#2412 feat: count chapter users in db
  client/graphql.schema.json
  client/src/components/ChapterCard.tsx
  client/src/generated/graphql.tsx
  client/src/modules/chapters/graphql/queries.ts
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  client/src/modules/home/graphql/queries.ts
  client/tests/ChapterCard.test.tsx
  server/src/controllers/Chapter/resolver.ts
  server/src/graphql-types/Chapter.ts
Labels: UI/UX, API, status: ready for review

#2418 test: using email link when initially logged out
  cypress/e2e/events/[eventId].cy.ts
Labels: status: ready for review

#2417 chore: clarify subscriptions
  client/src/modules/chapters/pages/chapterPage.tsx
  client/src/modules/events/pages/eventPage.tsx
  cypress/e2e/events/[eventId].cy.ts
Labels: UI/UX, status: ready for review
